### ISSUE TITLE
[Feature Request] - Nagios NRPE client adds.

### ISSUE THREAD

**Issue by karel-ii** [Gibbio/RPiTC_Builder#2]
Hi
I want to ask for feature to RPiTC builder.
I often need install NRPE client to terminal for remote monitoring.
Could you add this feature to RPITC ?

Install section:       apt-get install -y nagios-nrpe-server nagios-plugins
Uninstall section:  apt-get remove --purge -y nagios-nrpe-server nagios-plugins
Detect:                 /usr/sbin/nrpe

I created my own mod of RPiTC but i cant upload these files to git hub.

And i create script for rotating display. This script rotates touch panel also.. 

**rotate.sh**

```
#/bin/bash

boot_config="/boot/config.txt"

find=$(grep lcd_rotate $boot_config)

[[  -z  $find  ]] && printf "\nRotating of LCD display or LCD touch pannel\n#lcd_rotate=0\n" >> $boot_config 

case "$1" in
    "0")
        sed -i '/^#\?lcd_rotate/{s/^#\?lcd_rotate=[0-9]\{1\}/#lcd_rotate=0/}' $boot_config
        ;;
    "1")
        sed -i '/^#\?lcd_rotate/{s/^#\?lcd_rotate=[0-9]\{1\}/lcd_rotate=1/}' $boot_config
        ;;
    "2")
        sed -i '/^#\?lcd_rotate/{s/^#\?lcd_rotate=[0-9]\{1\}/lcd_rotate=2/}' $boot_config
        ;;
     "3")
        sed -i '/^#\?lcd_rotate/{s/^#\?lcd_rotate=[0-9]\{1\}/lcd_rotate=3/}' $boot_config
        ;;               
    *)
        exit 1;
        ;; 
esac
```

**Comment by Gibbio** [comment]
I'll include it in the next RPiTC Builder release, thanks!

**Comment by Gibbio** [comment]
integrated.
