### ISSUE TITLE
vmware horizon client

### ISSUE THREAD

**Issue by MiRHaDi** [Gibbio/RPiTC_Builder#3]
hi 
when i try to install vmware horizon client , wget will download a tar file and when i extract it , i have two file one enc and one elf !
enc is encrypted and elf can not open it !

**Comment by Gibbio** [comment]
wrong openssl md, fixed now. Try again, I've uploaded a new vmwh_LATEST package.

**Comment by MiRHaDi** [comment]
very thanks . its ok
