### ISSUE TITLE
VMWare in another os

### ISSUE THREAD

**Issue by MiRHaDi** [Gibbio/RPiTC_Builder#4]
hi
when i use RPiTC_Builder on RPiTC linux , thats ok .
but when i complile it on another linux ( for use RPI1 ) such as rasbian and run it , 
when i try to install vmware horizon client , "Segmentation fault" error is happen and vmware client not installed
please help me

**Comment by Gibbio** [comment]
package is for Raspberry Pi 2 or 3 only.

**Comment by MiRHaDi** [comment]
i want to setup vmware horizion client in another board !
such as rpi1 or orange pi , nano pi , banana pi , ....
please help me
